[MAIN]
# conta principal para manipulação do bot
conta_principal = seu_telefone

# canal que voce vai reagir
channel_username = seu_canal

# quantidade de contas que vai usar nos procedimentos
qtd_reactions = 5

# padrão 5 - apenas usado na função nº 3.
ultimas_mensagens = 5

# emojis que voce quer usar na operação, use emojis padrões e separe por virgulas!
reactions = 🔥,👍,😍,🥰,👍,🤩,👏,❤️

# tempo de cada reação - padrão 3s
time_reaction = 3